### ISSUE TITLE
Add compatibility with OSGi

### ISSUE THREAD

**Issue by baptistelebail** [vert-x3/vertx-reactive-streams#13]
Hello,

I'm using `vertx-core` and `vertx-web` which are both OSGi bundles, but `vertx-reactive-streams` is not.
Would it be possible to make it OSGi compatible ?

(I could provide a pull request if it's needed)

**Comment by tsegismont** [comment]
@baptistelebail sure, please go ahead

**Comment by tsegismont** [comment]
Fixed in #14
