### ISSUE TITLE
Concurrency issue with ReactiveWriteStreamImpl: pending Queue should be synchronized

### ISSUE THREAD

**Issue by crudolfs** [vert-x3/vertx-reactive-streams#15]
I'm facing concurrency issues when I use an async Subscriber (e.g. AWS SDK 2.5.64, which uses Netty under the hood) to subscribe to a ReactiveWriteStreamImpl. I'm using the Vertx Pipe to pipe the ReadStream data to the (Reactive)WriteStream.

The concurrency problem can be easily spotted by looking at the places where the pending Queue inside ReactiveWriteStreamImpl is read/modified and taking the reactive-streams pattern with non-blocking back pressure into account.

The problem is caused by the concurrent execution of pending.poll() within the checkSend() method of ReactiveWriteStreamImpl. This is caused by the fact that the checkSend() method is called from both the 'write' method AND the 'request' method within the SubscriptionImpl. As the request method is called (multiple times over time) by the Subscriber AND the write method is called by the Pipe (also multiple times over time) and both run on different threads, this leads sometimes to the pending.poll() returning a null (which results in a NullPointerException in the sendToSubscribers on item.value, because item is null).

A proposed fix for this issue would be to make the checkSend method synchronized.

**Comment by vietj** [comment]
can you make a test reproducing this ?

**Comment by aaloise** [comment]
How about using Optional instead of making the method synchronized? Something like:

```
Optional<Item<T>> opt = Optional.ofNullable(pending.poll);
opt.ifPresent(item -> sendToSubscribers(item);
```
