### ISSUE TITLE
Pipe documentation

### ISSUE THREAD

**Issue by aaloise** [vert-x3/vertx-reactive-streams#18]
In Vert.x reactive streams documentation there isn't any mention to the Stream Pipe API. There are practically only two places that Pipe can be found: the RFC link (https://github.com/vert-x3/wiki/wiki/RFC:-Stream-pipe-API) and Vert.x 3.7.0 announcement (https://vertx.io/blog/eclipse-vert-x-3-7-0-released/).

Docs could be updated, and maybe an example in vertx-examples repository

**Comment by vietj** [comment]
This is documented here https://vertx.io/docs/vertx-core/java/#streams

I think we should update example in vertx-examples that use Pump instead of Pipe. Do you fancy a contribution ?
