### ISSUE TITLE
Is there a Maven repository for these snapshots?

### ISSUE THREAD

**Issue by dancingfrog** [vert-x3/vertx-reactive-streams#8]
After adding the dependency info specified in the [documentation](https://github.com/vert-x3/vertx-reactive-streams/blob/master/src/main/asciidoc/java/index.adoc) to my pom.xml file and running ```mvn clean -U compile```, my build process fails with:
```
[WARNING] The POM for io.vertx:vertx-reactive-streams:jar:3.4.2-SNAPSHOT is missing, no dependency information available
```
Do I need to add a specific ```<repository>``` to use this snapshot?

**Comment by vietj** [comment]
yes you can find it on OSS sonatype snapshot repository : https://oss.sonatype.org/content/repositories/snapshots/
